package cn.ourwill.tuwenzb.mapper;

import cn.ourwill.tuwenzb.entity.Activity;
import org.apache.commons.lang3.StringUtils;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.jdbc.SQL;

import java.util.Map;

public class ActivityMapperProvider {

	//表名
	private String tableName="activity";

	//所有的列名
	private String columns="id,user_id,priority,title,introduction," +
			"start_time,end_time,site,organizer,publisher,generalize_status," +
			"generalize_name,generalize_link,phone,email,banner,watermark,water_complete,water_config,check_type,status," +
			"is_impower,qr_code,screen,docx,classical,model,c_time,u_time,type,show_start_time,show_end_time," +
			"icon_switch,is_auto_publish,switch_password,password,photo_live,face_set_token,is_open_face_search,iframe";

	//保存
	public String save(final Activity activity){
		return new SQL(){
			{
				INSERT_INTO(tableName);
				if(activity.getUserId()!=null){
					VALUES("user_id","#{userId}");
				}
				if(activity.getPriority()!=null){
					VALUES("priority","#{priority}");
				}
				if(activity.getTitle()!=null){
					VALUES("title","#{title}");
				}
				if(activity.getIntroduction()!=null){
					VALUES("introduction","#{introduction}");
				}
				if(activity.getStartTime()!=null){
					VALUES("start_time","#{startTime}");
				}
				if(activity.getEndTime()!=null){
					VALUES("end_time","#{endTime}");
				}
				if(activity.getSite()!=null){
					VALUES("site","#{site}");
				}
				if(activity.getOrganizer()!=null){
					VALUES("organizer","#{organizer}");
				}
				if(activity.getPublisher()!=null){
					VALUES("publisher","#{publisher}");
				}
				if(activity.getGeneralizeStatus()!=null){
					VALUES("generalize_status","#{generalizeStatus}");
				}
				if(activity.getGeneralizeName()!=null){
					VALUES("generalize_name","#{generalizeName}");
				}
				if(activity.getGeneralizeLink()!=null){
					VALUES("generalize_link","#{generalizeLink}");
				}
				if(activity.getPhone()!=null){
					VALUES("phone","#{phone}");
				}
				if(activity.getEmail()!=null){
					VALUES("email","#{email}");
				}
				if(activity.getBanner()!=null){
					VALUES("banner","#{banner}");
				}
				if(activity.getWatermark()!=null){
					VALUES("watermark","#{watermark}");
				}
				if(activity.getWaterComplete()!=null){
					VALUES("water_complete","#{waterComplete}");
				}
				if(activity.getWaterConfig()!=null){
					VALUES("water_config","#{waterConfig}");
				}
				if(activity.getCheckType()!=null){
					VALUES("check_type","#{checkType}");
				}
				if(activity.getStatus()!=null){
					VALUES("status","#{status}");
				}
				if(activity.getIsImpower()!=null){
					VALUES("is_impower","#{isImpower}");
				}
				if(activity.getQrCode()!=null){
					VALUES("qr_code","#{qrCode}");
				}
				if(activity.getScreen()!=null){
					VALUES("screen","#{screen}");
				}
				if(activity.getDocx()!=null){
					VALUES("docx","#{docx}");
				}
				if(activity.getClassical()!=null){
					VALUES("classical","#{classical}");
				}
				if(activity.getModel()!=null){
					VALUES("model","#{model}");
				}
				if(activity.getCTime()!=null){
					VALUES("c_time","#{cTime}");
				}
				if(activity.getUTime()!=null){
					VALUES("u_time","#{uTime}");
				}
				if(activity.getType()!=null){
					VALUES("type","#{type}");
				}
				if(activity.getShowStartTime()!=null){
					VALUES("show_start_time","#{showStartTime}");
				}
				if(activity.getEndTime()!=null){
					VALUES("show_end_time","#{showEndTime}");
				}
				if(activity.getIconSwitch()!=null){
					VALUES("icon_switch","#{iconSwitch}");
				}
				if(activity.getIsAutoPublish()!=null){
					VALUES("is_auto_publish","#{isAutoPublish}");
				}
				if(activity.getSwitchPassword()!=null){
					VALUES("switch_password","#{switchPassword}");
				}
				if(activity.getPassword()!=null){
					VALUES("password","#{password}");
				}
				if(activity.getPhotoLive()!=null){
					VALUES("photo_live","#{photoLive}");
				}
				if(activity.getIframe()!=null){
					VALUES("iframe","#{iframe}");
				}
				if(activity.getFaceSetToken()!=null){
					VALUES("face_set_token","#{faceSetToken}");
				}
				if(activity.getIsOpenFaceSearch()!=null){
					VALUES("is_open_face_search","#{isOpenFaceSearch}");
				}
			}
		}.toString();
	}
	//修改
	public String update(final Activity activity){
		return new SQL(){
			{
				UPDATE("activity");

				if(activity.getUserId()!=null){
					SET("user_id=#{userId}");
				}
				if(activity.getPriority()!=null){
					SET("priority=#{priority}");
				}
				if(activity.getTitle()!=null){
					SET("title=#{title}");
				}
				if(activity.getIntroduction()!=null){
					SET("introduction=#{introduction}");
				}
				if(activity.getStartTime()!=null){
					SET("start_time=#{startTime}");
				}
				if(activity.getEndTime()!=null){
					SET("end_time=#{endTime}");
				}
				if(activity.getSite()!=null){
					SET("site=#{site}");
				}
				if(activity.getOrganizer()!=null){
					SET("organizer=#{organizer}");
				}
				if(activity.getPublisher()!=null){
					SET("publisher=#{publisher}");
				}
				if(activity.getGeneralizeStatus()!=null){
					SET("generalize_status=#{generalizeStatus}");
				}
				if(activity.getGeneralizeName()!=null){
					SET("generalize_name=#{generalizeName}");
				}
				if(activity.getGeneralizeLink()!=null){
					SET("generalize_link=#{generalizeLink}");
				}
				if(activity.getPhone()!=null){
					SET("phone=#{phone}");
				}
				if(activity.getEmail()!=null){
					SET("email=#{email}");
				}
				if(activity.getBanner()!=null){
					SET("banner=#{banner}");
				}
				if(activity.getWatermark()!=null){
					SET("watermark=#{watermark}");
				}
				if(activity.getWaterComplete()!=null){
					SET("water_complete=#{waterComplete}");
				}
				if(activity.getWaterConfig()!=null){
					SET("water_config=#{waterConfig}");
				}
				if(activity.getCheckType()!=null){
					SET("check_type=#{checkType}");
				}
				if(activity.getIsImpower()!=null){
					SET("is_impower=#{isImpower}");
				}
				if(activity.getQrCode()!=null){
					SET("qr_code=#{qrCode}");
				}
				if(activity.getScreen()!=null){
					SET("screen=#{screen}");
				}
				if(activity.getDocx()!=null){
					SET("docx=#{docx}");
				}
				if(activity.getClassical()!=null){
					SET("classical=#{classical}");
				}
				if(activity.getModel()!=null){
					SET("model=#{model}");
				}
				if(activity.getCTime()!=null){
					SET("c_time=#{cTime}");
				}
				if(activity.getUTime()!=null){
					SET("u_time=#{uTime}");
				}
				if(activity.getType()!=null){
					SET("type=#{type}");
				}
				if(activity.getShowStartTime()!=null){
					SET("show_start_time=#{showStartTime}");
				}
				if(activity.getShowEndTime()!=null){
					SET("show_end_time=#{showEndTime}");
				}
				if(activity.getIconSwitch()!=null){
					SET("icon_switch=#{iconSwitch}");
				}
				if(activity.getIsAutoPublish()!=null){
					SET("is_auto_publish=#{isAutoPublish}");
				}
				if(activity.getSwitchPassword()!=null){
					SET("switch_password=#{switchPassword}");
				}
				if(activity.getPassword()!=null){
					SET("password=#{password}");
				}
				if(activity.getFaceSetToken()!=null){
					SET("face_set_token=#{faceSetToken}");
				}
				if(activity.getIsOpenFaceSearch()!=null){
					SET("is_open_face_search=#{isOpenFaceSearch}");
				}
				if(activity.getIframe()!=null){
					SET("iframe=#{iframe}");
				}
				if(activity.getExpectLikeNum()!=null){
					SET("expect_like_num=#{expectLikeNum}");
				}
				if(activity.getExpectParticipateNum()!=null){
					SET("expect_participate_num=#{expectParticipateNum}");
				}
				WHERE("id=#{id}");
			}
		}.toString();
	}
	//查找所有
	public String findAll(){
		return new SQL(){
			{
				SELECT("a.id,a.user_id,a.priority,title,a.introduction," +
						"a.start_time,a.end_time,site,a.organizer,a.publisher,a.generalize_status," +
								"a.generalize_name,a.generalize_link,a.phone,email,a.banner,a.watermark,a.water_complete,a.water_config,a.check_type,status," +
								"a.is_impower,a.qr_code,a.screen,docx,a.classical,a.model,a.c_time,a.u_time,a.type,a.show_start_time,a.show_end_time," +
						"t.type_name,a.icon_switch,a.switch_password,a.is_auto_publish,a.password,a.photo_live,a.face_set_token,a.is_open_face_search,a.iframe");
				FROM("activity a");
				LEFT_OUTER_JOIN("activity_type t on a.type = t.type");
			}
		}.toString();
	}

	//根据属性查找（使用user参数）
	public String findByProperty(final Activity activity){
		return new SQL(){
			{
				SELECT(columns);
				FROM("activity");
				if(activity.getId()!=null){
					WHERE("id=#{id}");
				}
				if(activity.getUserId()!=null){
					WHERE("user_id=#{userId}");
				}
				if(activity.getPriority()!=null){
					WHERE("priority=#{priority}");
				}
				if(activity.getTitle()!=null){
					WHERE("title=#{title}");
				}
				if(activity.getIntroduction()!=null){
					WHERE("introduction=#{introduction}");
				}
				if(activity.getStartTime()!=null){
					WHERE("start_time=#{startTime}");
				}
				if(activity.getEndTime()!=null){
					WHERE("end_time=#{endTime}");
				}
				if(activity.getSite()!=null){
					WHERE("site=#{site}");
				}
				if(activity.getOrganizer()!=null){
					WHERE("organizer=#{organizer}");
				}
				if(activity.getPublisher()!=null){
					WHERE("publisher=#{publisher}");
				}
				if(activity.getGeneralizeStatus()!=null){
					WHERE("generalize_status=#{generalizeStatus}");
				}
				if(activity.getGeneralizeName()!=null){
					WHERE("generalize_name=#{generalizeName}");
				}
				if(activity.getGeneralizeLink()!=null){
					WHERE("generalize_link=#{generalizeLink}");
				}
				if(activity.getPhone()!=null){
					WHERE("phone=#{phone}");
				}
				if(activity.getEmail()!=null){
					WHERE("email=#{email}");
				}
				if(activity.getBanner()!=null){
					WHERE("banner=#{banner}");
				}
				if(activity.getWatermark()!=null){
					WHERE("watermark=#{watermark}");
				}
				if(activity.getWaterComplete()!=null){
					WHERE("water_complete=#{waterComplete}");
				}
				if(activity.getWaterConfig()!=null){
					WHERE("water_config=#{waterConfig}");
				}
				if(activity.getCheckType()!=null){
					WHERE("check_type=#{checkType}");
				}
				if(activity.getStatus()!=null){
					WHERE("status=#{status}");
				}
				if(activity.getIsImpower()!=null){
					WHERE("is_impower=#{isImpower}");
				}
				if(activity.getQrCode()!=null){
					WHERE("qr_code=#{qrCode}");
				}
				if(activity.getScreen()!=null){
					WHERE("screen=#{screen}");
				}
				if(activity.getDocx()!=null){
					WHERE("docx=#{docx}");
				}
				if(activity.getClassical()!=null){
					WHERE("classical=#{classical}");
				}
				if(activity.getModel()!=null){
					WHERE("model=#{model}");
				}
				if(activity.getCTime()!=null){
					WHERE("c_time=#{cTime}");
				}
				if(activity.getUTime()!=null){
					WHERE("u_time=#{uTime}");
				}
				if(activity.getType()!=null){
					WHERE("type=#{type}");
				}
				if(activity.getShowStartTime()!=null){
					WHERE("show_start_time=#{showStartTime}");
				}
				if(activity.getShowEndTime()!=null){
					WHERE("show_end_time=#{showEndTime}");
				}
				if(activity.getIconSwitch()!=null){
					WHERE("icon_switch=#{iconSwitch}");
				}
				if(activity.getIsAutoPublish()!=null){
					WHERE("is_auto_publish=#{isAutoPublish}");
				}
				if(activity.getSwitchPassword()!=null){
					WHERE("switch_password=#{switchPassword}");
				}
				if(activity.getPassword()!=null){
					WHERE("password=#{password}");
				}
				if(activity.getFaceSetToken()!=null){
					WHERE("face_set_token=#{faceSetToken}");
				}
				if(activity.getIsOpenFaceSearch()!=null){
					WHERE("is_open_face_search=#{isOpenFaceSearch}");
				}
				if(activity.getIframe()!=null){
					WHERE("iframe=#{iframe}");
				}
			}
		}.toString();
	}

	//根据属性查找(使用Map参数)
	public String selectByParmer(final Map<String,Object> param){
		return new SQL(){
			{
				SELECT("(case when a.start_time>NOW() then 1 when a.end_time<NOW() then 0 else 2 end) as statuss,a.id,a.user_id,a.priority,a.title,a.introduction," +
						"a.start_time,a.end_time,a.site,a.organizer,a.publisher,a.generalize_status," +
						"a.generalize_name,a.generalize_link,a.phone,a.email,a.banner,a.watermark,a.water_complete,a.water_config,a.check_type,a.status," +
						"a.is_impower,a.qr_code,a.screen,docx,a.classical,a.model,a.c_time,a.u_time,a.type," +
						"a.show_start_time,a.show_end_time,t.type_name,a.icon_switch,a.is_auto_publish,a.switch_password,a.iframe," +
						"a.password,a.photo_live,a.face_set_token,a.is_open_face_search");
				FROM("activity a");
				LEFT_OUTER_JOIN("activity_type t on a.type = t.type");
				if(param.get("userName") != null && StringUtils.isNotEmpty(param.get("userName").toString())){
                    LEFT_OUTER_JOIN("user u on u.id = a.user_id");
                }
				if(param.get("id")!=null){
					WHERE("a.id=#{id}");
				}
				if(param.get("activityId")!=null){
					WHERE("a.activity_id=#{activityId}");
				}
				if(param.get("userId")!=null){
					WHERE("a.user_id=#{userId}");
				}
				if(param.get("priority")!=null){
					WHERE("a.priority=#{priority}");
				}
				if(param.get("title")!=null){
					WHERE("a.title=#{title}");
				}
				if(param.get("introduction")!=null){
					WHERE("a.introduction=#{introduction}");
				}
				if(param.get("startTime")!=null){
					WHERE("a.start_time=#{startTime}");
				}
				if(param.get("endTime")!=null){
					WHERE("a.end_time=#{endTime}");
				}
				if(param.get("site")!=null){
					WHERE("a.site=#{site}");
				}
				if(param.get("organizer")!=null){
					WHERE("a.organizer=#{organizer}");
				}
				if(param.get("publisher")!=null){
					WHERE("a.publisher=#{publisher}");
				}
				if(param.get("generalizeStatus")!=null){
					WHERE("a.generalize_status=#{generalizeStatus}");
				}
				if(param.get("generalizeName")!=null){
					WHERE("a.generalize_name=#{generalizeName}");
				}
				if(param.get("generalizeLink")!=null){
					WHERE("a.generalize_link=#{generalizeLink}");
				}
				if(param.get("phone")!=null){
					WHERE("a.phone=#{phone}");
				}
				if(param.get("email")!=null){
					WHERE("a.email=#{email}");
				}
				if(param.get("banner")!=null){
					WHERE("a.banner=#{banner}");
				}
				if(param.get("watermark")!=null){
					WHERE("a.watermark=#{watermark}");
				}
				if(param.get("waterComplete")!=null){
					WHERE("a.water_complete=#{waterComplete}");
				}
				if(param.get("waterConfig")!=null){
					WHERE("a.water_config=#{waterConfig}");
				}
				if(param.get("checkType")!=null){
					WHERE("a.check_type=#{checkType}");
				}
				if(param.get("status")!=null){
					WHERE("a.status=#{status}");
				}
				if(param.get("isImpower")!=null){
					WHERE("a.is_impower=#{isImpower}");
				}
				if(param.get("qrCode")!=null){
					WHERE("a.qr_code=#{qrCode}");
				}
				if(param.get("screen")!=null){
					WHERE("a.screen=#{screen}");
				}
				if(param.get("docx")!=null){
					WHERE("a.docx=#{docx}");
				}
				if(param.get("classical")!=null){
					WHERE("a.classical=#{classical}");
				}
				if(param.get("model")!=null){
					WHERE("a.model=#{model}");
				}
				if(param.get("cTime")!=null){
					WHERE("a.c_time=#{cTime}");
				}
				if(param.get("uTime")!=null){
					WHERE("a.u_time=#{uTime}");
				}
				if(param.get("type")!=null){
					WHERE("a.type=#{type}");
				}
				if(param.get("showStartTime")!=null){
					WHERE("a.show_start_time=#{showStartTime}");
				}
				if(param.get("showEndTime")!=null){
					WHERE("a.show_end_time=#{showEndTime}");
				}
				if(param.get("iconSwitch")!=null){
					WHERE("a.icon_switch=#{iconSwitch}");
				}
				if(param.get("isAutoPublish")!=null){
					WHERE("a.is_auto_publish=#{isAutoPublish}");
				}
				if(param.get("switchPassword")!=null){
					WHERE("a.switch_password=#{switchPassword}");
				}
				if(param.get("password")!=null){
					WHERE("a.password=#{password}");
				}
				if(param.get("photoLive")!=null){
					WHERE("a.photo_live=#{photoLive}");
				}
				if(param.get("faceSetToken")!=null){
					WHERE("a.face_set_token=#{faceSetToken}");
				}
				if(param.get("faceSetToken")!=null){
					WHERE("a.is_open_face_search=#{isOpenFaceSearch}");
				}
				if(param.get("iframe")!=null){
					WHERE("a.iframe=#{iframe}");
				}
				if( param.get("userName") != null && StringUtils.isNotEmpty(param.get("userName").toString())){
					WHERE("u.username = #{userName}");
				}
			}
		}.toString();
	}

	//根据ID查找
	public String selectById(Integer id){
		return new SQL(){
			{
				SELECT(columns);
				FROM("activity");
				WHERE("id=#{id}");
			}
		}.toString();
	}

	//根据id删除
	public String deleteById(Map param){
		return new SQL(){
			{
				DELETE_FROM("activity");
				WHERE("id=#{id}");
			}
		}.toString();
	}

	//根据用户ID查找
	public String selectByUserId(@Param("userId")Integer userId, @Param("photoLive") Integer photoLive){
		return new SQL(){
			{
				SELECT(columns);
				FROM("activity");
				WHERE("user_id=#{userId} and photo_live = #{photoLive} and status <> 3");
			}
		}.toString();
	}
}
