package com.souche.bmgateway.core.domain;

import java.math.BigDecimal;
import java.util.Date;

public class BillFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.business_date
     *
     * @mbggenerated
     */
    private String businessDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.serial_no
     *
     * @mbggenerated
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.stage_code
     *
     * @mbggenerated
     */
    private String stageCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.shop_code
     *
     * @mbggenerated
     */
    private String shopCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.shop_name
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.account_no
     *
     * @mbggenerated
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.account_name
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.trade_type
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.biz_type
     *
     * @mbggenerated
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.trade_amount
     *
     * @mbggenerated
     */
    private BigDecimal tradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.fee
     *
     * @mbggenerated
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.trade_status
     *
     * @mbggenerated
     */
    private Integer tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_flow.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.id
     *
     * @return the value of t_bill_flow.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.id
     *
     * @param id the value for t_bill_flow.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.business_date
     *
     * @return the value of t_bill_flow.business_date
     *
     * @mbggenerated
     */
    public String getBusinessDate() {
        return businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.business_date
     *
     * @param businessDate the value for t_bill_flow.business_date
     *
     * @mbggenerated
     */
    public void setBusinessDate(String businessDate) {
        this.businessDate = businessDate == null ? null : businessDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.serial_no
     *
     * @return the value of t_bill_flow.serial_no
     *
     * @mbggenerated
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.serial_no
     *
     * @param serialNo the value for t_bill_flow.serial_no
     *
     * @mbggenerated
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.order_code
     *
     * @return the value of t_bill_flow.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.order_code
     *
     * @param orderCode the value for t_bill_flow.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.stage_code
     *
     * @return the value of t_bill_flow.stage_code
     *
     * @mbggenerated
     */
    public String getStageCode() {
        return stageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.stage_code
     *
     * @param stageCode the value for t_bill_flow.stage_code
     *
     * @mbggenerated
     */
    public void setStageCode(String stageCode) {
        this.stageCode = stageCode == null ? null : stageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.shop_code
     *
     * @return the value of t_bill_flow.shop_code
     *
     * @mbggenerated
     */
    public String getShopCode() {
        return shopCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.shop_code
     *
     * @param shopCode the value for t_bill_flow.shop_code
     *
     * @mbggenerated
     */
    public void setShopCode(String shopCode) {
        this.shopCode = shopCode == null ? null : shopCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.shop_name
     *
     * @return the value of t_bill_flow.shop_name
     *
     * @mbggenerated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.shop_name
     *
     * @param shopName the value for t_bill_flow.shop_name
     *
     * @mbggenerated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.account_no
     *
     * @return the value of t_bill_flow.account_no
     *
     * @mbggenerated
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.account_no
     *
     * @param accountNo the value for t_bill_flow.account_no
     *
     * @mbggenerated
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.account_name
     *
     * @return the value of t_bill_flow.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.account_name
     *
     * @param accountName the value for t_bill_flow.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.trade_type
     *
     * @return the value of t_bill_flow.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.trade_type
     *
     * @param tradeType the value for t_bill_flow.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.biz_type
     *
     * @return the value of t_bill_flow.biz_type
     *
     * @mbggenerated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.biz_type
     *
     * @param bizType the value for t_bill_flow.biz_type
     *
     * @mbggenerated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.trade_amount
     *
     * @return the value of t_bill_flow.trade_amount
     *
     * @mbggenerated
     */
    public BigDecimal getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.trade_amount
     *
     * @param tradeAmount the value for t_bill_flow.trade_amount
     *
     * @mbggenerated
     */
    public void setTradeAmount(BigDecimal tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.fee
     *
     * @return the value of t_bill_flow.fee
     *
     * @mbggenerated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.fee
     *
     * @param fee the value for t_bill_flow.fee
     *
     * @mbggenerated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.trade_status
     *
     * @return the value of t_bill_flow.trade_status
     *
     * @mbggenerated
     */
    public Integer getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.trade_status
     *
     * @param tradeStatus the value for t_bill_flow.trade_status
     *
     * @mbggenerated
     */
    public void setTradeStatus(Integer tradeStatus) {
        this.tradeStatus = tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.source
     *
     * @return the value of t_bill_flow.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.source
     *
     * @param source the value for t_bill_flow.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_flow.gmt_create
     *
     * @return the value of t_bill_flow.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_flow.gmt_create
     *
     * @param gmtCreate the value for t_bill_flow.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}