package com.souche.bmgateway.core.domain;

import java.math.BigDecimal;
import java.util.Date;

public class DeductionRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.business_date
     *
     * @mbggenerated
     */
    private String businessDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.request_no
     *
     * @mbggenerated
     */
    private String requestNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.trade_type
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.trade_amount
     *
     * @mbggenerated
     */
    private BigDecimal tradeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.currency
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.trade_status
     *
     * @mbggenerated
     */
    private Integer tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.payer_account
     *
     * @mbggenerated
     */
    private String payerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.payer_name
     *
     * @mbggenerated
     */
    private String payerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.shop_code
     *
     * @mbggenerated
     */
    private String shopCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.shop_name
     *
     * @mbggenerated
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.payee_account
     *
     * @mbggenerated
     */
    private String payeeAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.payee_name
     *
     * @mbggenerated
     */
    private String payeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.summary_id
     *
     * @mbggenerated
     */
    private Integer summaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_deduction_record.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.id
     *
     * @return the value of t_deduction_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.id
     *
     * @param id the value for t_deduction_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.business_date
     *
     * @return the value of t_deduction_record.business_date
     *
     * @mbggenerated
     */
    public String getBusinessDate() {
        return businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.business_date
     *
     * @param businessDate the value for t_deduction_record.business_date
     *
     * @mbggenerated
     */
    public void setBusinessDate(String businessDate) {
        this.businessDate = businessDate == null ? null : businessDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.request_no
     *
     * @return the value of t_deduction_record.request_no
     *
     * @mbggenerated
     */
    public String getRequestNo() {
        return requestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.request_no
     *
     * @param requestNo the value for t_deduction_record.request_no
     *
     * @mbggenerated
     */
    public void setRequestNo(String requestNo) {
        this.requestNo = requestNo == null ? null : requestNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.order_no
     *
     * @return the value of t_deduction_record.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.order_no
     *
     * @param orderNo the value for t_deduction_record.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.trade_type
     *
     * @return the value of t_deduction_record.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.trade_type
     *
     * @param tradeType the value for t_deduction_record.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.trade_amount
     *
     * @return the value of t_deduction_record.trade_amount
     *
     * @mbggenerated
     */
    public BigDecimal getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.trade_amount
     *
     * @param tradeAmount the value for t_deduction_record.trade_amount
     *
     * @mbggenerated
     */
    public void setTradeAmount(BigDecimal tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.currency
     *
     * @return the value of t_deduction_record.currency
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.currency
     *
     * @param currency the value for t_deduction_record.currency
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.trade_status
     *
     * @return the value of t_deduction_record.trade_status
     *
     * @mbggenerated
     */
    public Integer getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.trade_status
     *
     * @param tradeStatus the value for t_deduction_record.trade_status
     *
     * @mbggenerated
     */
    public void setTradeStatus(Integer tradeStatus) {
        this.tradeStatus = tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.payer_account
     *
     * @return the value of t_deduction_record.payer_account
     *
     * @mbggenerated
     */
    public String getPayerAccount() {
        return payerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.payer_account
     *
     * @param payerAccount the value for t_deduction_record.payer_account
     *
     * @mbggenerated
     */
    public void setPayerAccount(String payerAccount) {
        this.payerAccount = payerAccount == null ? null : payerAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.payer_name
     *
     * @return the value of t_deduction_record.payer_name
     *
     * @mbggenerated
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.payer_name
     *
     * @param payerName the value for t_deduction_record.payer_name
     *
     * @mbggenerated
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.shop_code
     *
     * @return the value of t_deduction_record.shop_code
     *
     * @mbggenerated
     */
    public String getShopCode() {
        return shopCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.shop_code
     *
     * @param shopCode the value for t_deduction_record.shop_code
     *
     * @mbggenerated
     */
    public void setShopCode(String shopCode) {
        this.shopCode = shopCode == null ? null : shopCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.shop_name
     *
     * @return the value of t_deduction_record.shop_name
     *
     * @mbggenerated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.shop_name
     *
     * @param shopName the value for t_deduction_record.shop_name
     *
     * @mbggenerated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.payee_account
     *
     * @return the value of t_deduction_record.payee_account
     *
     * @mbggenerated
     */
    public String getPayeeAccount() {
        return payeeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.payee_account
     *
     * @param payeeAccount the value for t_deduction_record.payee_account
     *
     * @mbggenerated
     */
    public void setPayeeAccount(String payeeAccount) {
        this.payeeAccount = payeeAccount == null ? null : payeeAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.payee_name
     *
     * @return the value of t_deduction_record.payee_name
     *
     * @mbggenerated
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.payee_name
     *
     * @param payeeName the value for t_deduction_record.payee_name
     *
     * @mbggenerated
     */
    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName == null ? null : payeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.remark
     *
     * @return the value of t_deduction_record.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.remark
     *
     * @param remark the value for t_deduction_record.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.summary_id
     *
     * @return the value of t_deduction_record.summary_id
     *
     * @mbggenerated
     */
    public Integer getSummaryId() {
        return summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.summary_id
     *
     * @param summaryId the value for t_deduction_record.summary_id
     *
     * @mbggenerated
     */
    public void setSummaryId(Integer summaryId) {
        this.summaryId = summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.gmt_create
     *
     * @return the value of t_deduction_record.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.gmt_create
     *
     * @param gmtCreate the value for t_deduction_record.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_deduction_record.gmt_modify
     *
     * @return the value of t_deduction_record.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_deduction_record.gmt_modify
     *
     * @param gmtModify the value for t_deduction_record.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}