package com.souche.bmgateway.core.domain;

import java.util.Date;

public class OrderShareApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.req_msg_id
     *
     * @mbggenerated
     */
    private String reqMsgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.payment_order_no
     *
     * @mbggenerated
     */
    private String paymentOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.tm_order_no
     *
     * @mbggenerated
     */
    private String tmOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.merchant_id
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.member_id
     *
     * @mbggenerated
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.relate_order_no
     *
     * @mbggenerated
     */
    private String relateOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.share_order_no
     *
     * @mbggenerated
     */
    private String shareOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.share_date
     *
     * @mbggenerated
     */
    private String shareDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.total_amount
     *
     * @mbggenerated
     */
    private String totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.currency
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.payer_fund_details
     *
     * @mbggenerated
     */
    private String payerFundDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.payee_fund_details
     *
     * @mbggenerated
     */
    private String payeeFundDetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.apply_status
     *
     * @mbggenerated
     */
    private String applyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.notify_status
     *
     * @mbggenerated
     */
    private String notifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.query_times
     *
     * @mbggenerated
     */
    private Integer queryTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.ext_info
     *
     * @mbggenerated
     */
    private String extInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.extension
     *
     * @mbggenerated
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_share_apply.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.id
     *
     * @return the value of t_order_share_apply.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.id
     *
     * @param id the value for t_order_share_apply.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.out_trade_no
     *
     * @return the value of t_order_share_apply.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.out_trade_no
     *
     * @param outTradeNo the value for t_order_share_apply.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.req_msg_id
     *
     * @return the value of t_order_share_apply.req_msg_id
     *
     * @mbggenerated
     */
    public String getReqMsgId() {
        return reqMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.req_msg_id
     *
     * @param reqMsgId the value for t_order_share_apply.req_msg_id
     *
     * @mbggenerated
     */
    public void setReqMsgId(String reqMsgId) {
        this.reqMsgId = reqMsgId == null ? null : reqMsgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.payment_order_no
     *
     * @return the value of t_order_share_apply.payment_order_no
     *
     * @mbggenerated
     */
    public String getPaymentOrderNo() {
        return paymentOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.payment_order_no
     *
     * @param paymentOrderNo the value for t_order_share_apply.payment_order_no
     *
     * @mbggenerated
     */
    public void setPaymentOrderNo(String paymentOrderNo) {
        this.paymentOrderNo = paymentOrderNo == null ? null : paymentOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.tm_order_no
     *
     * @return the value of t_order_share_apply.tm_order_no
     *
     * @mbggenerated
     */
    public String getTmOrderNo() {
        return tmOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.tm_order_no
     *
     * @param tmOrderNo the value for t_order_share_apply.tm_order_no
     *
     * @mbggenerated
     */
    public void setTmOrderNo(String tmOrderNo) {
        this.tmOrderNo = tmOrderNo == null ? null : tmOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.merchant_id
     *
     * @return the value of t_order_share_apply.merchant_id
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.merchant_id
     *
     * @param merchantId the value for t_order_share_apply.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.member_id
     *
     * @return the value of t_order_share_apply.member_id
     *
     * @mbggenerated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.member_id
     *
     * @param memberId the value for t_order_share_apply.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.relate_order_no
     *
     * @return the value of t_order_share_apply.relate_order_no
     *
     * @mbggenerated
     */
    public String getRelateOrderNo() {
        return relateOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.relate_order_no
     *
     * @param relateOrderNo the value for t_order_share_apply.relate_order_no
     *
     * @mbggenerated
     */
    public void setRelateOrderNo(String relateOrderNo) {
        this.relateOrderNo = relateOrderNo == null ? null : relateOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.share_order_no
     *
     * @return the value of t_order_share_apply.share_order_no
     *
     * @mbggenerated
     */
    public String getShareOrderNo() {
        return shareOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.share_order_no
     *
     * @param shareOrderNo the value for t_order_share_apply.share_order_no
     *
     * @mbggenerated
     */
    public void setShareOrderNo(String shareOrderNo) {
        this.shareOrderNo = shareOrderNo == null ? null : shareOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.share_date
     *
     * @return the value of t_order_share_apply.share_date
     *
     * @mbggenerated
     */
    public String getShareDate() {
        return shareDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.share_date
     *
     * @param shareDate the value for t_order_share_apply.share_date
     *
     * @mbggenerated
     */
    public void setShareDate(String shareDate) {
        this.shareDate = shareDate == null ? null : shareDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.total_amount
     *
     * @return the value of t_order_share_apply.total_amount
     *
     * @mbggenerated
     */
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.total_amount
     *
     * @param totalAmount the value for t_order_share_apply.total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount == null ? null : totalAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.currency
     *
     * @return the value of t_order_share_apply.currency
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.currency
     *
     * @param currency the value for t_order_share_apply.currency
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.payer_fund_details
     *
     * @return the value of t_order_share_apply.payer_fund_details
     *
     * @mbggenerated
     */
    public String getPayerFundDetails() {
        return payerFundDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.payer_fund_details
     *
     * @param payerFundDetails the value for t_order_share_apply.payer_fund_details
     *
     * @mbggenerated
     */
    public void setPayerFundDetails(String payerFundDetails) {
        this.payerFundDetails = payerFundDetails == null ? null : payerFundDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.payee_fund_details
     *
     * @return the value of t_order_share_apply.payee_fund_details
     *
     * @mbggenerated
     */
    public String getPayeeFundDetails() {
        return payeeFundDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.payee_fund_details
     *
     * @param payeeFundDetails the value for t_order_share_apply.payee_fund_details
     *
     * @mbggenerated
     */
    public void setPayeeFundDetails(String payeeFundDetails) {
        this.payeeFundDetails = payeeFundDetails == null ? null : payeeFundDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.apply_status
     *
     * @return the value of t_order_share_apply.apply_status
     *
     * @mbggenerated
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.apply_status
     *
     * @param applyStatus the value for t_order_share_apply.apply_status
     *
     * @mbggenerated
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus == null ? null : applyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.notify_status
     *
     * @return the value of t_order_share_apply.notify_status
     *
     * @mbggenerated
     */
    public String getNotifyStatus() {
        return notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.notify_status
     *
     * @param notifyStatus the value for t_order_share_apply.notify_status
     *
     * @mbggenerated
     */
    public void setNotifyStatus(String notifyStatus) {
        this.notifyStatus = notifyStatus == null ? null : notifyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.query_times
     *
     * @return the value of t_order_share_apply.query_times
     *
     * @mbggenerated
     */
    public Integer getQueryTimes() {
        return queryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.query_times
     *
     * @param queryTimes the value for t_order_share_apply.query_times
     *
     * @mbggenerated
     */
    public void setQueryTimes(Integer queryTimes) {
        this.queryTimes = queryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.ext_info
     *
     * @return the value of t_order_share_apply.ext_info
     *
     * @mbggenerated
     */
    public String getExtInfo() {
        return extInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.ext_info
     *
     * @param extInfo the value for t_order_share_apply.ext_info
     *
     * @mbggenerated
     */
    public void setExtInfo(String extInfo) {
        this.extInfo = extInfo == null ? null : extInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.memo
     *
     * @return the value of t_order_share_apply.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.memo
     *
     * @param memo the value for t_order_share_apply.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.extension
     *
     * @return the value of t_order_share_apply.extension
     *
     * @mbggenerated
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.extension
     *
     * @param extension the value for t_order_share_apply.extension
     *
     * @mbggenerated
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.gmt_create
     *
     * @return the value of t_order_share_apply.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.gmt_create
     *
     * @param gmtCreate the value for t_order_share_apply.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_share_apply.gmt_modified
     *
     * @return the value of t_order_share_apply.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_share_apply.gmt_modified
     *
     * @param gmtModified the value for t_order_share_apply.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}