package com.souche.bmgateway.core.domain;

import java.util.Date;

public class PayRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_request.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_request.business_date
     *
     * @mbggenerated
     */
    private String businessDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_request.task_code
     *
     * @mbggenerated
     */
    private String taskCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_request.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_request.trade_status
     *
     * @mbggenerated
     */
    private Integer tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_request.total_num
     *
     * @mbggenerated
     */
    private Integer totalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_request.success_num
     *
     * @mbggenerated
     */
    private Integer successNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_request.fail_num
     *
     * @mbggenerated
     */
    private Integer failNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_request.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_request.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_request.id
     *
     * @return the value of t_pay_request.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_request.id
     *
     * @param id the value for t_pay_request.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_request.business_date
     *
     * @return the value of t_pay_request.business_date
     *
     * @mbggenerated
     */
    public String getBusinessDate() {
        return businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_request.business_date
     *
     * @param businessDate the value for t_pay_request.business_date
     *
     * @mbggenerated
     */
    public void setBusinessDate(String businessDate) {
        this.businessDate = businessDate == null ? null : businessDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_request.task_code
     *
     * @return the value of t_pay_request.task_code
     *
     * @mbggenerated
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_request.task_code
     *
     * @param taskCode the value for t_pay_request.task_code
     *
     * @mbggenerated
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_request.version
     *
     * @return the value of t_pay_request.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_request.version
     *
     * @param version the value for t_pay_request.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_request.trade_status
     *
     * @return the value of t_pay_request.trade_status
     *
     * @mbggenerated
     */
    public Integer getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_request.trade_status
     *
     * @param tradeStatus the value for t_pay_request.trade_status
     *
     * @mbggenerated
     */
    public void setTradeStatus(Integer tradeStatus) {
        this.tradeStatus = tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_request.total_num
     *
     * @return the value of t_pay_request.total_num
     *
     * @mbggenerated
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_request.total_num
     *
     * @param totalNum the value for t_pay_request.total_num
     *
     * @mbggenerated
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_request.success_num
     *
     * @return the value of t_pay_request.success_num
     *
     * @mbggenerated
     */
    public Integer getSuccessNum() {
        return successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_request.success_num
     *
     * @param successNum the value for t_pay_request.success_num
     *
     * @mbggenerated
     */
    public void setSuccessNum(Integer successNum) {
        this.successNum = successNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_request.fail_num
     *
     * @return the value of t_pay_request.fail_num
     *
     * @mbggenerated
     */
    public Integer getFailNum() {
        return failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_request.fail_num
     *
     * @param failNum the value for t_pay_request.fail_num
     *
     * @mbggenerated
     */
    public void setFailNum(Integer failNum) {
        this.failNum = failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_request.gmt_create
     *
     * @return the value of t_pay_request.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_request.gmt_create
     *
     * @param gmtCreate the value for t_pay_request.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_request.gmt_modify
     *
     * @return the value of t_pay_request.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_request.gmt_modify
     *
     * @param gmtModify the value for t_pay_request.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}