package com.souche.bmgateway.core.domain;

public class TaskInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.task_code
     *
     * @mbggenerated
     */
    private String taskCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.task_name
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.payer_account
     *
     * @mbggenerated
     */
    private String payerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.payer_name
     *
     * @mbggenerated
     */
    private String payerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.payee_account
     *
     * @mbggenerated
     */
    private String payeeAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.payee_name
     *
     * @mbggenerated
     */
    private String payeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.payee_bank_code
     *
     * @mbggenerated
     */
    private String payeeBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.payee_bank_name
     *
     * @mbggenerated
     */
    private String payeeBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.is_live
     *
     * @mbggenerated
     */
    private String isLive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.id
     *
     * @return the value of t_task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.id
     *
     * @param id the value for t_task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.task_code
     *
     * @return the value of t_task.task_code
     *
     * @mbggenerated
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.task_code
     *
     * @param taskCode the value for t_task.task_code
     *
     * @mbggenerated
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.task_name
     *
     * @return the value of t_task.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.task_name
     *
     * @param taskName the value for t_task.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.payer_account
     *
     * @return the value of t_task.payer_account
     *
     * @mbggenerated
     */
    public String getPayerAccount() {
        return payerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.payer_account
     *
     * @param payerAccount the value for t_task.payer_account
     *
     * @mbggenerated
     */
    public void setPayerAccount(String payerAccount) {
        this.payerAccount = payerAccount == null ? null : payerAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.payer_name
     *
     * @return the value of t_task.payer_name
     *
     * @mbggenerated
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.payer_name
     *
     * @param payerName the value for t_task.payer_name
     *
     * @mbggenerated
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.payee_account
     *
     * @return the value of t_task.payee_account
     *
     * @mbggenerated
     */
    public String getPayeeAccount() {
        return payeeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.payee_account
     *
     * @param payeeAccount the value for t_task.payee_account
     *
     * @mbggenerated
     */
    public void setPayeeAccount(String payeeAccount) {
        this.payeeAccount = payeeAccount == null ? null : payeeAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.payee_name
     *
     * @return the value of t_task.payee_name
     *
     * @mbggenerated
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.payee_name
     *
     * @param payeeName the value for t_task.payee_name
     *
     * @mbggenerated
     */
    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName == null ? null : payeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.payee_bank_code
     *
     * @return the value of t_task.payee_bank_code
     *
     * @mbggenerated
     */
    public String getPayeeBankCode() {
        return payeeBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.payee_bank_code
     *
     * @param payeeBankCode the value for t_task.payee_bank_code
     *
     * @mbggenerated
     */
    public void setPayeeBankCode(String payeeBankCode) {
        this.payeeBankCode = payeeBankCode == null ? null : payeeBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.payee_bank_name
     *
     * @return the value of t_task.payee_bank_name
     *
     * @mbggenerated
     */
    public String getPayeeBankName() {
        return payeeBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.payee_bank_name
     *
     * @param payeeBankName the value for t_task.payee_bank_name
     *
     * @mbggenerated
     */
    public void setPayeeBankName(String payeeBankName) {
        this.payeeBankName = payeeBankName == null ? null : payeeBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.remark
     *
     * @return the value of t_task.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.remark
     *
     * @param remark the value for t_task.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.is_live
     *
     * @return the value of t_task.is_live
     *
     * @mbggenerated
     */
    public String getIsLive() {
        return isLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.is_live
     *
     * @param isLive the value for t_task.is_live
     *
     * @mbggenerated
     */
    public void setIsLive(String isLive) {
        this.isLive = isLive == null ? null : isLive.trim();
    }
}