package com.souche.bmgateway.core.dao;

import com.souche.bmgateway.core.domain.BillFlow;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BillFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_flow
     *
     * @mbggenerated
     */
    int insert(BillFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_flow
     *
     * @mbggenerated
     */
    int insertSelective(BillFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_flow
     *
     * @mbggenerated
     */
    BillFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BillFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BillFlow record);

    BillFlow selectSelective(BillFlow record);

    /**
     * 获取账单流水
     */
    List<BillFlow> selectListByBizType(@Param("businessDate") String businessDate,
                                       @Param("bizType") String bizType, @Param("serialNo") String serialNo);
}