package com.souche.bmgateway.core.dao;

import com.souche.bmgateway.core.domain.BillSummary;
import com.souche.bmgateway.core.domain.SettleTranSumInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BillSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_summary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_summary
     *
     * @mbggenerated
     */
    int insert(BillSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_summary
     *
     * @mbggenerated
     */
    int insertSelective(BillSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_summary
     *
     * @mbggenerated
     */
    BillSummary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_summary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BillSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bill_summary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BillSummary record);

    /**
     * 根据类型获取账单列表
     *
     * @param bizType
     * @return
     */
    List<BillSummary> getBillSummaryByType(@Param("lastPosition") Integer lastPosition
            , @Param("bizType") String bizType,
                                           @Param("position") Integer position, @Param("requestNum") Integer requestNum,
                                           @Param("status") List<Integer> status);

    /**
     * 更新状态
     */
    int updateStatusByType(@Param("businessDate") String businessDate,
                           @Param("bizType") String bizType, @Param("status") Integer status);

    /**
     * 获取汇总账单并保存
     */
    int insertBillSummary(@Param("businessDate") String businessDate, @Param("bizType") String bizType,
                          @Param("batchId") String batchId);

    int updateStatusByIDList(@Param("list") List<Integer> list, @Param("status") Integer status);

    /**
     * 获取这一批代发统计条数
     *
     * @param lastPosition 上一次代发到此id
     */
    SettleTranSumInfo getSettleTranSumInfo(@Param("lastPosition") Integer lastPosition, @Param("bizType") String bizType);

    /**
     * 获取上次代发的id
     *
     * @param businessDate 20180908
     */
    Integer getLastTaskPosition(String businessDate);


    /**
     * 根据批次号做统计
     */
    SettleTranSumInfo getSettleTranSumInfoByDeductionDate(@Param("businessDate") String businessDate, @Param("type") String type);

}