package com.souche.bmgateway.core.dao;

import com.souche.bmgateway.core.domain.DeductionRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeductionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deduction_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deduction_record
     *
     * @mbggenerated
     */
    int insert(DeductionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deduction_record
     *
     * @mbggenerated
     */
    int insertSelective(DeductionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deduction_record
     *
     * @mbggenerated
     */
    DeductionRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deduction_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeductionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_deduction_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeductionRecord record);
    /**
     * 批量插入扣款记录
     */
    int batchInsertRecords(List<DeductionRecord> list);

    /**
     * 更新扣款记录状态, orderNo非必填, 不填的时候更新一批
     */
    int updateStatusByBatchId(@Param("requestNo") String requestNo, @Param("orderNo") String orderNo, @Param("tradeStatus") Integer tradeStatus);

    /**
     * 获取记录记录
     */
    DeductionRecord selectByOrderNo(@Param("requestNo") String requestNo, @Param("orderNo")String orderNo);
}