package com.souche.bmgateway.core.dao;

import com.souche.bmgateway.core.domain.Holiday;
import org.apache.ibatis.annotations.Param;

public interface HolidayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     */
    int insert(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     */
    int insertSelective(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     */
    Holiday selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     */
    int updateByPrimaryKeySelective(Holiday record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_holiday
     */
    int updateByPrimaryKey(Holiday record);

    /**
     * 返回某年某月的节假日
     *
     * @param year  y
     * @param month M
     * @return 1, 2, 3, 4...
     */
    String getHolidayDaysByYearAndMonth(@Param("year") Integer year, @Param("month") Integer month);
}