package com.souche.bmgateway.core.dao;

import com.souche.bmgateway.core.domain.OrderShareApply;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderShareApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_share_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_share_apply
     *
     * @mbggenerated
     */
    int insert(OrderShareApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_share_apply
     *
     * @mbggenerated
     */
    int insertSelective(OrderShareApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_share_apply
     *
     * @mbggenerated
     */
    OrderShareApply selectByPrimaryKey(Long id);

    /**
     * 查询分账通知结果处理中的分账
     *
     * @param queryTimes
     * @param count
     * @return
     */
    List<OrderShareApply> selectNotSuccessStatus(@Param("queryTimes") int queryTimes, @Param("count") int count);

    /**
     * 根据分账请求号更新申请状态
     *
     * @param outTradeNo
     * @param applyStatus
     * @return
     */
    int updateApplyStatusByOutTradeNo(@Param("outTradeNo") String outTradeNo, @Param("applyStatus") String applyStatus);

    /**
     * 根据请求流水号查询
     *
     * @param outTradeNo
     * @return
     */
    OrderShareApply selectByOutTradeNo(@Param("outTradeNo") String outTradeNo);


    /**
     * 根据外部交易号更新网商分账订单号
     *
     * @param outTradeNo
     * @param shareOrderNo
     * @return
     */
    int updateShareOrderNo(@Param("outTradeNo") String outTradeNo, @Param("shareOrderNo") String shareOrderNo);

    /**
     * 更新分账申请网商返回的结果信息
     *
     * @param outTradeNo
     * @param shareOrderNo
     * @param applyStatus
     * @param extension
     * @return
     */
    int updateShareApplyResult(@Param("outTradeNo") String outTradeNo, @Param("shareOrderNo") String shareOrderNo, @Param("applyStatus") String applyStatus, @Param("extension") String extension);

    /**
     * 更新网商分帐通知返回的结果信息
     *
     * @param outTradeNo
     * @param shareDate
     * @param notifyStatus
     * @return
     */
    int updateShareNotifyResult(@Param("outTradeNo") String outTradeNo, @Param("notifyStatus") String notifyStatus, @Param("shareDate") String shareDate);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_share_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderShareApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_share_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderShareApply record);
}